services:
  baah:
    build:
      context: .
      # dockerfile: Dockerfile.CN
    container_name: BAAH
    volumes:
      - ./BAAH_CONFIGS:/app/BAAH_CONFIGS
    environment:
      - TZ=Asia/Shanghai
      - HOST=0.0.0.0
      - PORT=8000
      # - TOKEN=YOUR_TOKEN
    ports:
      - 8000:8000
